INSERT INTO BUILDING(ID, NAME) VALUES(-1, 'Building1');
INSERT INTO BUILDING(ID, NAME) VALUES(-2, 'Building2');

INSERT INTO ROOM(ID, NAME, FLOOR, BUILDING_ID) VALUES(-10, 'Room1', 1, -1);
INSERT INTO ROOM(ID, NAME, FLOOR, BUILDING_ID) VALUES(-9, 'Room2', 1, -1);

INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (1, 8, 'OFF', -10);
INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (2, 0, 'OFF', -10);

INSERT INTO HMDT_SENSOR(ID, HUMIDITY) VALUES(1, 0);
INSERT INTO HMDT_SENSOR(ID, HUMIDITY) VALUES(2, 0);

INSERT INTO TEMP_SENSOR(ID, TEMPERATURE) VALUES(1, 0);
INSERT INTO TEMP_SENSOR(ID, TEMPERATURE) VALUES(2, 0);